version: "{build}"

build: off

clone_folder: /usr/go/src/github.com/$username/$project

environment:
  GOPATH: /usr/go/

stack: go 1.10, go 1.11, go 1.12

before_test:
  - go vet ./...

test_script:
  - go test ./...
